name: Pre submits publish policy
on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions: read-all

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Install policy engine
        uses: waynekoo/slsa-policy/actions/installer@v0.0.1

      - name: Validate publish policy
        working-directory: policies/publish
        run: |
          set -euo pipefail
          slsa-policy publish validate org.json .
